name: trainapp
description: "Train Booking Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # QR Scanner
  mobile_scanner: ^5.2.3

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10

  # QR Code
  qr_flutter: ^4.1.0

  # Maps
  google_maps_flutter: ^2.14.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Fonts
  google_fonts: ^6.2.1

  # State Management
  provider: ^6.1.5+1

  # Utilities
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/alexandria.jpg
    - assets/images/aswan.jpg
    - assets/images/luxor.jpg
    - assets/images/assiut.jpg
    - assets/images/portsaid.jpg
    - assets/images/mansoura.jpg
    - assets/images/tanta.jpg
    - assets/images/suez.jpg
    - assets/images/train_background.jpg
    - assets/images/logo.png